### ISSUE TITLE
Unknown node type figure!

### ISSUE THREAD

**Issue by linjiX** [dzhu/rstfmt#10]
reStructuredText supports directive `figure`:
https://docutils.sourceforge.io/docs/ref/rst/directives.html#figure

But `rstfmt` reports a traceback about it:
```bash
$ rstfmt index.rst
Traceback (most recent call last):
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 730, in fmt
    func = getattr(Formatters, type(node).__name__)
AttributeError: type object 'Formatters' has no attribute 'figure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/linji/.pyenv/versions/3.8.2/bin/rstfmt", line 8, in <module>
    sys.exit(main())
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/main.py", line 53, in main
    output = rstfmt.format_node(args.width, doc)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 739, in format_node
    return "\n".join(fmt(node, FormatContext(0, width, "", "", [], 0))) + "\n"
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 482, in document
    yield from chain_intersperse("", fmt_children(node, ctx))
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 75, in chain_intersperse
    yield from x
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 478, in section
    yield from chain_intersperse("", fmt_children(node, ctx.in_section()))
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 71, in chain_intersperse
    for x in it:
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 209, in <genexpr>
    return (fmt(c, ctx) for c in node.children)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 732, in fmt
    raise ValueError(f"Unknown node type {type(node).__name__}!")
ValueError: Unknown node type figure!
```

Here is the `index.rst`:
```rst
######
 Test
######

.. figure:: ./000000.png
   :scale: 50 %
   :align: center

   caption

```

**Comment by dzhu** [comment]
Hi, and thanks for your interest! This should be working in version 0.0.9, now available on PyPI. I finally got around to figuring out how to handle all of the standard directives automatically without listing them out individually.
