### ISSUE TITLE
Broken due to Sphinx 4.0 release

### ISSUE THREAD

**Issue by tpansino** [dzhu/rstfmt#12]
It looks like Sphinx 4.0 was released May 9, 2020, which broke `rstfmt`.

```bash
$ rstfmt
Traceback (most recent call last):
  File "/usr/local/bin/rstfmt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/rstfmt/__main__.py", line 36, in main
    rst_extras.register()
  File "/usr/local/lib/python3.9/site-packages/rstfmt/rst_extras.py", line 145, in register
    _add_directive("literalinclude", sphinx.directives.code.LiteralInclude)
  File "/usr/local/lib/python3.9/site-packages/sphinx/deprecation.py", line 52, in __getattr__
    return getattr(self._module, name)
AttributeError: module 'sphinx.directives' has no attribute 'code'
```

I did some initial triage, but I don't see the problem, the `code.py` file is still there. :shrug: 

I recommend adding something like `sphinx>=2.4.0, <4.0` to your `install_requires` in `setup.py`. Or when you fix it, `sphinx>=2.4.0, <5.0`. :slightly_smiling_face:

**Comment by dzhu** [comment]
Thanks for the report! Sorry for the delay, but t
his should be fixed in version 0.0.10, now available on PyPI.
