### ISSUE TITLE
Unknown directive type "literalinclude"

### ISSUE THREAD

**Issue by linjiX** [dzhu/rstfmt#7]
sphinx supports the directive type "literalinclude": 
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude

But if the rst file includes the directive "literalinclude", rstfmt will report a traceback:
```bash
$ rstfmt index.rst
:5: (ERROR/3) Unknown directive type "literalinclude".

.. literalinclude:: test.txt
Traceback (most recent call last):
  File "/Users/linji/.pyenv/versions/3.8.2/bin/rstfmt", line 8, in <module>
    sys.exit(main())
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/main.py", line 40, in main
    doc = rstfmt.parse_string(inp)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 706, in parse_string
    parser.parse(s, doc)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 3005, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construc
t
    return method(self, expmatch)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    return self.unknown_directive(type_name)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2280, in unknown_directive
    error = self.reporter.error(
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/utils/__init__.py", line 231, in error
    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/rstfmt/rstfmt.py", line 274, in system_message
    msg = super().system_message(level, message, *children, **kwargs)
  File "/Users/linji/.pyenv/versions/3.8.2/lib/python3.8/site-packages/docutils/utils/__init__.py", line 197, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: :5: (ERROR/3) Unknown directive type "literalinclude".

.. literalinclude:: test.txt
```

The index.rst file looks like:
```rst
######
 Test
######

.. literalinclude:: test.txt
```

**Comment by dzhu** [comment]
Thanks for your interest, and sorry for the delay! This should be fixed in version 0.0.8, which is now available on PyPI, so I'm closing the issue. Feel free to comment here or open a new issue if anything goes wrong.
