### ISSUE TITLE
Substitution with images do not work properly

### ISSUE THREAD

**Issue by kayhayen** [dzhu/rstfmt#9]
Hello,

I am using this: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#substitution-definitions

My example is this:

```
Debian/Ubuntu/Mint
~~~~~~~~~~~~~~~~~~

* |DEBIAN_LOGO| |UBUNTU_LOGO| |MINT_LOGO| Stable: Debian/Ubuntu/Mint
  repositories

.. |DEBIAN_LOGO| image:: images/debian.png

.. |UBUNTU_LOGO| image:: images/ubuntu.png

.. |MINT_LOGO| image:: images/mint.png
```

on my download page, this should work, but gives a traceback like this:

```
:588: (WARNING/2) Substitution definition "DEBIAN_LOGO" empty or invalid.

.. |DEBIAN_LOGO| image:: images/debian.png

Traceback (most recent call last):
  File "/usr/local/bin/rstfmt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/rstfmt/main.py", line 40, in main
    doc = rstfmt.parse_string(inp)
  File "/usr/local/lib/python3.7/dist-packages/rstfmt/rstfmt.py", line 752, in parse_string
    parser.parse(s, doc)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 172, in run
    input_source=document['source'])
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2754, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2329, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2359, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 320, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2632, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2339, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2060, in substitution_def
    source=src, line=srcline)
  File "/usr/lib/python3/dist-packages/docutils/utils/__init__.py", line 221, in warning
    return self.system_message(self.WARNING_LEVEL, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rstfmt/rstfmt.py", line 274, in system_message
    msg = super().system_message(level, message, *children, **kwargs)
  File "/usr/lib/python3/dist-packages/docutils/utils/__init__.py", line 194, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: :588: (WARNING/2) Substitution definition "DEBIAN_LOGO" empty or invalid.

.. |DEBIAN_LOGO| image:: images/debian.png
```

**Comment by dzhu** [comment]
Thanks for the report! This should be fixed in version 0.0.9.
